"use client";

import { useState } from "react";
import Icon from "@/components/dashboard/Icon";
import { Card, EmptyState, PageHeader, SearchInput, StatusBadge } from "@/components/ui/DashboardUI";

export default function ManagementPage({ role, kind, title, description, rows, action }) {
  const [query, setQuery] = useState("");
  const filteredRows = rows.filter((row) => `${row.title} ${row.subtitle} ${row.meta}`.toLowerCase().includes(query.toLowerCase()));
  const isInstructor = role === "instructor";
  return <div className="space-y-7"><PageHeader eyebrow={isInstructor ? "My workspace" : "Content operations"} title={isInstructor && kind === "courses" ? "My Courses" : title} description={isInstructor ? `Manage your own ${kind} and prepare the next learning experience.` : description} action={action} /><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="w-full sm:max-w-xs"><SearchInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${kind}...`} /></div><div className="flex items-center gap-2 text-xs text-slate-500"><span>{filteredRows.length} records</span><button type="button" className="rounded-lg border border-slate-800 p-2 text-slate-400 hover:border-orange-500/50 hover:text-orange-300" aria-label="More filters"><Icon name="dots" size={17} /></button></div></div>{filteredRows.length ? <Card className="overflow-hidden"><div className="hidden grid-cols-[minmax(0,1.5fr)_minmax(120px,1fr)_140px_90px] gap-4 border-b border-slate-800 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-600 md:grid"><span>{kind === "users" ? "User" : "Title"}</span><span>Context</span><span>Details</span><span>Status</span></div><div className="divide-y divide-slate-800/70">{filteredRows.map((row) => <div key={row.title} className="grid gap-3 px-5 py-4 md:grid-cols-[minmax(0,1.5fr)_minmax(120px,1fr)_140px_90px] md:items-center md:gap-4"><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-200">{row.title}</p><p className="mt-1 truncate text-xs text-slate-500">{row.subtitle}</p></div><p className="text-xs text-slate-400">{row.meta}</p><div className="flex items-center justify-between md:justify-start"><span className="text-xs text-slate-500">Updated recently</span><button type="button" className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-800 hover:text-orange-300" aria-label={`Actions for ${row.title}`}><Icon name="dots" size={16} /></button></div><StatusBadge status={row.status} /></div>)}</div></Card> : <EmptyState title={`No ${kind} found`} description="Your search returned no results. Connected content will appear here when available." />}</div>;
}
