"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Card, EmptyState, PageHeader, SearchInput } from "@/components/ui/DashboardUI";
import Icon from "@/components/dashboard/Icon";
import { deleteQuiz, getQuizzes, normalizeQuiz } from "@/services/strapi/quizzes";

export default function QuizManagement({ role }) {
  const [quizzes, setQuizzes] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("loading"); const [error, setError] = useState("");
  const load = useCallback(async () => { setStatus("loading"); try { const response = await getQuizzes({ search: query }); setQuizzes((response?.data || []).map(normalizeQuiz)); setStatus("ready"); } catch (loadError) { console.error("[quizzes] Failed to load quizzes", loadError); setError(loadError.message || "Unable to load quizzes."); setStatus("error"); } }, [query]);
  useEffect(() => { load(); }, [load]);
  async function remove(quiz) { if (!window.confirm(`Are you sure you want to delete "${quiz.title}"?`)) return; try { await deleteQuiz(quiz.documentId || quiz.id); await load(); } catch (deleteError) { console.error("[quizzes] Failed to delete quiz", deleteError); setError(deleteError.message || "Unable to delete quiz."); } }
  return <div className="space-y-7"><PageHeader eyebrow={role === "instructor" ? "My workspace" : "Content operations"} title="Quiz Management" description="Build and maintain course assessments." action={<Link href={`/dashboard/${role}/quizzes/create`} className="inline-flex items-center gap-2 rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-semibold text-white"><Icon name="plus" size={16} />Create Quiz</Link>} /><SearchInput value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search quizzes..." />{error && <p role="alert" className="text-sm text-red-300">{error}</p>}{status === "loading" ? <Card className="animate-pulse p-8"><div className="h-32 rounded bg-slate-800" /></Card> : quizzes.length === 0 ? <EmptyState title="No quizzes found" description="Create a quiz from a course to start assessing learners." /> : <Card className="overflow-hidden"><div className="divide-y divide-slate-800/70">{quizzes.map((quiz) => <div key={quiz.documentId || quiz.id} className="flex flex-col gap-4 px-5 py-5 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/dashboard/${role}/quizzes/${quiz.documentId || quiz.id}`} className="text-sm font-semibold text-slate-200 hover:text-orange-300">{quiz.title}</Link><p className="mt-1 text-xs text-slate-500">{quiz.questions.length} questions · {quiz.timelimit} minutes · {quiz.quizNo || "Auto-numbered"}</p></div><div className="flex flex-wrap gap-2"><Link href={`/dashboard/${role}/quizzes/${quiz.documentId || quiz.id}`} className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-400 hover:bg-slate-800">View</Link><Link href={`/dashboard/${role}/quizzes/${quiz.documentId || quiz.id}/edit`} className="rounded-lg px-3 py-2 text-xs font-semibold text-orange-300 hover:bg-orange-500/10">Edit</Link><button type="button" onClick={() => remove(quiz)} className="rounded-lg px-3 py-2 text-xs font-semibold text-red-300 hover:bg-red-500/10">Delete</button></div></div>)}</div></Card>}</div>;
}
