"use client";

import { useState } from "react";
import Icon from "@/components/dashboard/Icon";
import { Card, PageHeader } from "@/components/ui/DashboardUI";

export default function QuizCreatePage({ role }) {
  const [saved, setSaved] = useState(false);
  return <div className="space-y-7"><PageHeader eyebrow={role === "instructor" ? "My content" : "Assessment studio"} title="Create Quiz" description="Draft a knowledge check now. Questions and publishing will connect to Strapi later." /><Card className="max-w-3xl p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-xs font-semibold text-slate-300 sm:col-span-2">Quiz title<input className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950/70 px-3 py-3 text-sm font-normal text-slate-200 outline-none focus:border-orange-500/60" placeholder="e.g. App Router assessment" /></label><label className="space-y-2 text-xs font-semibold text-slate-300">Course<select className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950/70 px-3 py-3 text-sm font-normal text-slate-300 outline-none focus:border-orange-500/60"><option>Next.js Mastery</option><option>Machine Learning Foundations</option></select></label><label className="space-y-2 text-xs font-semibold text-slate-300">Lesson<select className="mt-1 w-full rounded-xl border border-slate-800 bg-slate-950/70 px-3 py-3 text-sm font-normal text-slate-300 outline-none focus:border-orange-500/60"><option>Layouts and loading states</option><option>Routing and layouts</option></select></label><label className="space-y-2 text-xs font-semibold text-slate-300 sm:col-span-2">Description<textarea rows="4" className="mt-1 w-full resize-none rounded-xl border border-slate-800 bg-slate-950/70 px-3 py-3 text-sm font-normal text-slate-300 outline-none focus:border-orange-500/60" placeholder="What should learners demonstrate?" /></label></div><div className="mt-6 flex flex-col-reverse gap-3 border-t border-slate-800 pt-5 sm:flex-row sm:justify-end"><button type="button" className="rounded-xl border border-slate-700 px-4 py-2.5 text-xs font-semibold text-slate-300 hover:border-orange-500/50 hover:text-orange-300">Save as draft</button><button type="button" onClick={() => setSaved(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-amber-400 px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-orange-500/10 hover:brightness-110"><Icon name="check" size={14} />{saved ? "Draft saved" : "Create quiz"}</button></div></Card></div>;
}
